# Generated by Django 5.0.6 on 2024-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_formdata_form_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(default='testing@example.com', max_length=32),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='message',
            field=models.TextField(default='this is testing message', max_length=2000),
        ),
    ]
